import { Link } from "@tanstack/react-router";

const LAST_UPDATED = "April 26, 2026";

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: "#F5F3EE" }}>
      <header className="border-b border-[#E8E5DF] bg-white">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="text-lg font-bold text-[#0F0F0F]">HireSort</Link>
          <nav className="flex items-center gap-5 text-sm">
            <Link to="/privacy" className="text-[#737373] hover:text-[#0F0F0F]">Privacy</Link>
            <Link to="/login" className="text-[#0F0F0F] font-medium">Sign in</Link>
          </nav>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <p className="text-xs uppercase tracking-wider text-[#C85A17] font-semibold mb-2">Legal</p>
        <h1 className="text-3xl font-bold text-[#0F0F0F] mb-2">Terms of Service</h1>
        <p className="text-sm text-[#737373] mb-10">Last updated: {LAST_UPDATED}</p>

        <Section title="1. Acceptance of Terms">
          <p>
            These Terms of Service (the &ldquo;Terms&rdquo;) form a binding agreement between you and HireSort
            (&ldquo;HireSort&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;) governing your access to and use of the
            HireSort platform, website, and related services (collectively, the &ldquo;Service&rdquo;).
            By creating an account or using the Service, you agree to be bound by these Terms.
            If you do not agree, do not use the Service.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            HireSort is a recruitment-assistance platform that uses artificial intelligence to help
            employers and recruiters analyse job descriptions, evaluate resumes against
            customer-defined criteria, and rank candidates. The Service is decision-support
            software intended to assist hiring teams; it does not make hiring decisions.
          </p>
        </Section>

        <Section title="3. Eligibility and Business Use">
          <p>
            The Service is offered solely for business and professional recruitment use. By
            using the Service you represent that you (a) are at least 18 years old, (b) have
            authority to bind the organisation on whose behalf you use the Service, and
            (c) will use the Service only for lawful recruitment purposes.
          </p>
        </Section>

        <Section title="4. Accounts and Security">
          <p>
            You are responsible for safeguarding your account credentials and for all activity
            that occurs under your account. Notify us immediately at the contact address below
            if you suspect unauthorised access. We may suspend accounts to protect the Service
            or other users.
          </p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to:</p>
          <ul>
            <li>Upload candidate information you are not authorised to process;</li>
            <li>Use the Service to discriminate in violation of applicable employment law;</li>
            <li>Reverse-engineer, scrape, or attempt to extract the underlying models or source code;</li>
            <li>Resell, sublicense, or expose the Service to third parties as a standalone product;</li>
            <li>Upload malware or content that infringes third-party rights;</li>
            <li>Interfere with the Service or attempt to circumvent rate limits or quotas.</li>
          </ul>
        </Section>

        <Section title="6. Customer Data and Ownership">
          <p>
            You retain all rights in the resumes, job descriptions, candidate notes, and other
            materials you submit (&ldquo;Customer Data&rdquo;). You grant HireSort a limited, worldwide,
            non-exclusive licence to host, process, and transmit Customer Data solely to provide
            and improve the Service for you. You are the data controller for Customer Data; we
            act as your data processor and process such data only on your documented instructions.
          </p>
        </Section>

        <Section title="7. AI-Assisted Screening — Decision Support Only">
          <p>
            Candidate scoring and ranking produced by the Service are generated by AI models and
            are intended as <strong>decision support, not as final hiring decisions</strong>. You
            agree that a human will review and make all material employment decisions. You are
            responsible for complying with all laws applicable to automated employment decision
            tools in your jurisdiction, including (without limitation) the EU AI Act, NYC Local
            Law 144, the Illinois AI Video Interview Act, India&apos;s Digital Personal Data
            Protection Act 2023, and analogous regulations.
          </p>
        </Section>

        <Section title="8. Subscriptions, Billing and Refunds">
          <p>
            Paid plans are billed in advance through our payment processor (Razorpay). Quotas
            (such as resumes processed per cycle) reset on the renewal date and unused quota
            does not roll over. Except where required by law, fees are non-refundable. You may
            cancel at any time; cancellation takes effect at the end of the current billing
            period.
          </p>
        </Section>

        <Section title="9. Service Availability">
          <p>
            We use commercially reasonable efforts to keep the Service available, but we do
            not guarantee uninterrupted operation. The Service is provided on an
            &ldquo;as available&rdquo; basis. Defined uptime commitments are available only under a
            separately executed enterprise agreement.
          </p>
        </Section>

        <Section title="10. Intellectual Property">
          <p>
            The Service, including all software, models, designs, and trademarks, is and
            remains the exclusive property of HireSort and its licensors. No rights are granted
            to you except as expressly set out in these Terms. Feedback you provide may be used
            by us without obligation.
          </p>
        </Section>

        <Section title="11. Confidentiality">
          <p>
            Each party will protect the other&apos;s non-public information using at least the
            same degree of care it uses for its own confidential information, and in no event
            less than reasonable care.
          </p>
        </Section>

        <Section title="12. Disclaimer of Warranties">
          <p>
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND,
            WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT THE SERVICE WILL BE
            ERROR-FREE OR UNINTERRUPTED.
          </p>
        </Section>

        <Section title="13. Limitation of Liability">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, HIRESORT&apos;S AGGREGATE LIABILITY ARISING
            OUT OF OR RELATING TO THESE TERMS WILL NOT EXCEED THE FEES PAID BY YOU TO HIRESORT
            IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM. NEITHER
            PARTY WILL BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
            DAMAGES, OR FOR LOST PROFITS, REVENUE, OR DATA.
          </p>
        </Section>

        <Section title="14. Indemnification">
          <p>
            You will defend and indemnify HireSort against any claim brought by a third party
            (including any candidate) arising from your Customer Data, your use of the Service
            in violation of these Terms or applicable law, or your hiring decisions.
          </p>
        </Section>

        <Section title="15. Termination">
          <p>
            Either party may terminate these Terms at any time. Upon termination, your right
            to access the Service ceases immediately. We will delete Customer Data within
            ninety (90) days of termination unless a longer period is required by law.
            Sections that by their nature should survive termination will survive.
          </p>
        </Section>

        <Section title="16. Changes to These Terms">
          <p>
            We may modify these Terms from time to time. Material changes will be notified by
            email or through the Service at least thirty (30) days before they take effect.
            Continued use after the effective date constitutes acceptance.
          </p>
        </Section>

        <Section title="17. Governing Law and Disputes">
          <p>
            These Terms are governed by the laws of India, without regard to conflict-of-laws
            principles. The courts at Bengaluru, Karnataka shall have exclusive jurisdiction,
            subject to any rights you may have under mandatory consumer-protection law.
          </p>
        </Section>

        <Section title="18. Contact">
          <p>
            Questions about these Terms can be sent to{" "}
            <a href="mailto:support@hiresort.app" className="text-[#0F0F0F] underline">support@hiresort.app</a>.
          </p>
        </Section>

        <div className="mt-12 pt-6 border-t border-[#E8E5DF] text-xs text-[#A0A0A0]">
          <p>
            <Link to="/" className="hover:text-[#0F0F0F]">&larr; Back to home</Link>
            <span className="mx-2">·</span>
            <Link to="/privacy" className="hover:text-[#0F0F0F]">Privacy Policy</Link>
          </p>
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-base font-bold text-[#0F0F0F] mb-3">{title}</h2>
      <div className="text-sm text-[#404040] leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1 [&_ul]:text-[#404040]">
        {children}
      </div>
    </section>
  );
}
